version: "3.9"

services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo-teste
    networks:
      - minha-rede
  
  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks-teste
    networks:
      - minha-rede
    ports:
      - 3000:3000
    depends_on: 
      - mongodb  

networks:
  minha-rede:
    driver: bridge